### ISSUE TITLE
Only shares one item

### ISSUE THREAD

**Issue by hsw28** [jordanmoconnor/poshshare#2]
As far as I can tell.. don't know javascript so can't be of much help... too bad it's not in python

**Comment by jordanmoconnor** [comment]
The updated code is here: https://onepercentgrowth.com/blog/poshmark-automation/

**Comment by dtjellybird** [comment]
The update is prompting me to confirm each share - is that the intent? thanks for the script hb

**Comment by jordanmoconnor** [comment]
It shouldn't. They may have updated the website! I'll have to test it, but I haven't heard any other complaints.

**Comment by hsw28** [comment]
whoops sorry forgot to update that your updated code worked fine. thanks and sorry!! and chance you wanna make one for following people :D ?
